services:
  client_web:
    build:
      context: ./django_client/
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./django_client/blog_services/:/usr/src/app/
      - client_static_files:/usr/src/app/staticfiles

  user_write_api:
    build:
      context: ./django_restfull/user_write_api/
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./django_restfull/user_write_api/:/usr/src/app/
      - api_static_files:/usr/src/app/staticfiles
    depends_on:
      - db

  user_read_api:
    build:
      context: ./django_restfull/user_read_api
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./django_restfull/user_read_api/:/usr/src/app/
      - api_static_files:/usr/src/app/staticfiles
    depends_on:
      - db

  feed_write_api:
    build:
      context: ./django_restfull/feed_write_api/
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./django_restfull/feed_write_api/:/usr/src/app/
      - api_static_files:/usr/src/app/staticfiles
    depends_on:
      - db

  feed_read_api:
    build:
      context: ./django_restfull/feed_read_api/
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./django_restfull/feed_read_api/:/usr/src/app/
      - api_static_files:/usr/src/app/staticfiles
    depends_on:
      - db


  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - client_static_files:/home/app/client/staticfiles
      - api_static_files:/home/app/api/staticfiles

  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=arabians_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=whiskey
    container_name: postgres_db

volumes:
  client_static_files:
  api_static_files:
